# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_get_projects_users200_response_data import CustodianGetProjectsUsers200ResponseData

class TestCustodianGetProjectsUsers200ResponseData(unittest.TestCase):
    """CustodianGetProjectsUsers200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianGetProjectsUsers200ResponseData:
        """Test CustodianGetProjectsUsers200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianGetProjectsUsers200ResponseData`
        """
        model = CustodianGetProjectsUsers200ResponseData()
        if include_optional:
            return CustodianGetProjectsUsers200ResponseData(
                current_page = 1,
                per_page = 25,
                total = 3,
                data = [
                    safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner.custodianGetProjectsUsers_200_response_data_data_inner(
                        project_id = 1, 
                        user_digital_ident = '$2y$12...', 
                        project_role_id = 7, 
                        primary_contact = False, 
                        affiliation_id = 1, 
                        role = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_role.custodianGetProjectsUsers_200_response_data_data_inner_role(
                            id = 8, 
                            name = 'Student', ), 
                        affiliation = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_affiliation.custodianGetProjectsUsers_200_response_data_data_inner_affiliation(
                            id = 1, 
                            organisation_id = 1, 
                            organisation = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_affiliation_organisation.custodianGetProjectsUsers_200_response_data_data_inner_affiliation_organisation(
                                id = 1, 
                                organisation_name = 'Health Pathways (UK) Limited', ), ), 
                        registry = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_registry.custodianGetProjectsUsers_200_response_data_data_inner_registry(
                            id = 1, 
                            digi_ident = '$2y$12...', 
                            verified = False, 
                            user = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_registry_user.custodianGetProjectsUsers_200_response_data_data_inner_registry_user(
                                id = 10, 
                                first_name = 'Dan', 
                                last_name = 'Ackroyd', 
                                email = 'dan@example.com', 
                                status = 'registered', ), ), 
                        project = safepeopleregistry_api_sdk.models.custodian_get_projects_users_200_response_data_data_inner_project.custodianGetProjectsUsers_200_response_data_data_inner_project(
                            id = 2, 
                            title = 'Assessing Air Quality Impact...', ), )
                    ],
                first_page_url = 'http://localhost/api/v1/custodians/1/projects_users?page=1',
                last_page_url = 'http://localhost/api/v1/custodians/1/projects_users?page=1',
                next_page_url = '',
                prev_page_url = ''
            )
        else:
            return CustodianGetProjectsUsers200ResponseData(
        )
        """

    def testCustodianGetProjectsUsers200ResponseData(self):
        """Test CustodianGetProjectsUsers200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
