# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation200_response_data import AffiliationsGetOrganisationAffiliation200ResponseData

class TestAffiliationsGetOrganisationAffiliation200ResponseData(unittest.TestCase):
    """AffiliationsGetOrganisationAffiliation200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliationsGetOrganisationAffiliation200ResponseData:
        """Test AffiliationsGetOrganisationAffiliation200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliationsGetOrganisationAffiliation200ResponseData`
        """
        model = AffiliationsGetOrganisationAffiliation200ResponseData()
        if include_optional:
            return AffiliationsGetOrganisationAffiliation200ResponseData(
                id = 123,
                registry_id = 1,
                organisation_id = 100,
                model_state_id = 2,
                model_state = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_model_state.affiliationsGetOrganisationAffiliation_200_response_data_model_state(
                    id = 2, 
                    state_id = 5, 
                    state = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_model_state_state.affiliationsGetOrganisationAffiliation_200_response_data_model_state_state(
                        id = 5, 
                        name = 'Approved', ), ),
                organisation = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_organisation.affiliationsGetOrganisationAffiliation_200_response_data_organisation(
                    id = 100, 
                    organisation_name = 'Example Org', 
                    unclaimed = False, 
                    lead_applicant_email = 'lead@example.org', )
            )
        else:
            return AffiliationsGetOrganisationAffiliation200ResponseData(
        )
        """

    def testAffiliationsGetOrganisationAffiliation200ResponseData(self):
        """Test AffiliationsGetOrganisationAffiliation200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
