# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_index200_response import CustodianIndex200Response

class TestCustodianIndex200Response(unittest.TestCase):
    """CustodianIndex200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianIndex200Response:
        """Test CustodianIndex200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianIndex200Response`
        """
        model = CustodianIndex200Response()
        if include_optional:
            return CustodianIndex200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.custodian.Custodian(
                    id = 1, 
                    created_at = '2023-10-10T15:03:00Z', 
                    updated_at = '2023-10-10T15:03:00Z', 
                    name = 'Custodian Name', 
                    unique_identifier = 'aVl9jMgJHQjZz0xMOJ56hNyJJm9nIjm51TSf7Wp6', 
                    contact_email = 'key.contact.email@email.com', 
                    enabled = True, 
                    invite_accepted_at = '2023-10-10T15:03:00Z', 
                    invite_sent_at = '2023-10-10T15:03:00Z', 
                    idvt_required = False, 
                    gateway_app_id = 'HfjmY6rOymGjQwGcPkXIghYOggDcV1A83no4pbZp', 
                    gateway_client_id = 'RTWSlsx8iuQxN6JmfKFkopyWF8wfeKNt4tkuJcS3', 
                    client_id = '1111-2222-3333-4444-5555', )
            )
        else:
            return CustodianIndex200Response(
        )
        """

    def testCustodianIndex200Response(self):
        """Test CustodianIndex200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
