# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisations_get_status404_response import OrganisationsGetStatus404Response

class TestOrganisationsGetStatus404Response(unittest.TestCase):
    """OrganisationsGetStatus404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationsGetStatus404Response:
        """Test OrganisationsGetStatus404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationsGetStatus404Response`
        """
        model = OrganisationsGetStatus404Response()
        if include_optional:
            return OrganisationsGetStatus404Response(
                message = 'Organisation not found'
            )
        else:
            return OrganisationsGetStatus404Response(
        )
        """

    def testOrganisationsGetStatus404Response(self):
        """Test OrganisationsGetStatus404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
