# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.query_api import QueryApi


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueryApi()

    def tearDown(self) -> None:
        pass

    def test_query_query(self) -> None:
        """Test case for query_query

        Query@query
        """
        pass


if __name__ == '__main__':
    unittest.main()
