# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.project_user_api import ProjectUserApi


class TestProjectUserApi(unittest.TestCase):
    """ProjectUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectUserApi()

    def tearDown(self) -> None:
        pass

    def test_project_user_show(self) -> None:
        """Test case for project_user_show

        Get project user details
        """
        pass


if __name__ == '__main__':
    unittest.main()
