# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_model_config_get_entity_models404_response import CustodianModelConfigGetEntityModels404Response

class TestCustodianModelConfigGetEntityModels404Response(unittest.TestCase):
    """CustodianModelConfigGetEntityModels404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianModelConfigGetEntityModels404Response:
        """Test CustodianModelConfigGetEntityModels404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianModelConfigGetEntityModels404Response`
        """
        model = CustodianModelConfigGetEntityModels404Response()
        if include_optional:
            return CustodianModelConfigGetEntityModels404Response(
                message = 'No entity models found'
            )
        else:
            return CustodianModelConfigGetEntityModels404Response(
        )
        """

    def testCustodianModelConfigGetEntityModels404Response(self):
        """Test CustodianModelConfigGetEntityModels404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
