# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.custodian_project_users_api import CustodianProjectUsersApi


class TestCustodianProjectUsersApi(unittest.TestCase):
    """CustodianProjectUsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustodianProjectUsersApi()

    def tearDown(self) -> None:
        pass

    def test_custodian_project_users_index(self) -> None:
        """Test case for custodian_project_users_index

        List all project users associated with a custodian
        """
        pass

    def test_custodian_project_users_show(self) -> None:
        """Test case for custodian_project_users_show

        Get custodian approval for a project user
        """
        pass

    def test_custodian_project_users_update(self) -> None:
        """Test case for custodian_project_users_update

        Update custodian approval for a project user
        """
        pass


if __name__ == '__main__':
    unittest.main()
