# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.validation_checks_api import ValidationChecksApi


class TestValidationChecksApi(unittest.TestCase):
    """ValidationChecksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationChecksApi()

    def tearDown(self) -> None:
        pass

    def test_validation_checks_destroy(self) -> None:
        """Test case for validation_checks_destroy

        Delete a validation check
        """
        pass

    def test_validation_checks_index(self) -> None:
        """Test case for validation_checks_index

        List all validation checks
        """
        pass

    def test_validation_checks_show(self) -> None:
        """Test case for validation_checks_show

        Get a single validation check
        """
        pass

    def test_validation_checks_store(self) -> None:
        """Test case for validation_checks_store

        Create a new validation check
        """
        pass

    def test_validation_checks_update(self) -> None:
        """Test case for validation_checks_update

        Update a validation check
        """
        pass


if __name__ == '__main__':
    unittest.main()
