# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.organisation_api import OrganisationApi


class TestOrganisationApi(unittest.TestCase):
    """OrganisationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganisationApi()

    def tearDown(self) -> None:
        pass

    def test_organisation_get_delegates(self) -> None:
        """Test case for organisation_get_delegates

        Return all delegates associated with an organisation
        """
        pass

    def test_organisation_get_projects(self) -> None:
        """Test case for organisation_get_projects

        organisation@getProjects
        """
        pass

    def test_organisation_get_sponsorships_projects(self) -> None:
        """Test case for organisation_get_sponsorships_projects

        organisation@getSponsorshipsProjects
        """
        pass

    def test_organisation_get_users(self) -> None:
        """Test case for organisation_get_users

        organisation@getUsers
        """
        pass

    def test_organisation_index(self) -> None:
        """Test case for organisation_index

        organisation@index
        """
        pass


if __name__ == '__main__':
    unittest.main()
