# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_project_destroy(self) -> None:
        """Test case for project_destroy

        Project@destroy
        """
        pass

    def test_project_get_all_users_flag_project_by_user_id(self) -> None:
        """Test case for project_get_all_users_flag_project_by_user_id

        Get all users by projectID and userID
        """
        pass

    def test_project_get_project_by_id_and_organisation_id(self) -> None:
        """Test case for project_get_project_by_id_and_organisation_id

        Get project details by projectID and organisationID
        """
        pass

    def test_project_get_project_by_id_and_user_id(self) -> None:
        """Test case for project_get_project_by_id_and_user_id

        Get project details by projectID and userID
        """
        pass

    def test_project_get_project_users(self) -> None:
        """Test case for project_get_project_users

        Project@getProjectUsers
        """
        pass

    def test_project_get_project_users_by_organisation_id(self) -> None:
        """Test case for project_get_project_users_by_organisation_id

        Get all users by projectID and organisationID
        """
        pass

    def test_project_index(self) -> None:
        """Test case for project_index

        Project@index
        """
        pass

    def test_project_make_primary_contact(self) -> None:
        """Test case for project_make_primary_contact

        Project@edit
        """
        pass

    def test_project_show(self) -> None:
        """Test case for project_show

        Project@show
        """
        pass

    def test_project_store(self) -> None:
        """Test case for project_store

        Project@store
        """
        pass

    def test_project_update(self) -> None:
        """Test case for project_update

        Project@update
        """
        pass

    def test_project_update_all_project_users(self) -> None:
        """Test case for project_update_all_project_users

        Project@updateAllProjectUsers
        """
        pass


if __name__ == '__main__':
    unittest.main()
