# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.query_query200_response_data_user import QueryQuery200ResponseDataUser

class TestQueryQuery200ResponseDataUser(unittest.TestCase):
    """QueryQuery200ResponseDataUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryQuery200ResponseDataUser:
        """Test QueryQuery200ResponseDataUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryQuery200ResponseDataUser`
        """
        model = QueryQuery200ResponseDataUser()
        if include_optional:
            return QueryQuery200ResponseDataUser(
                id = 10,
                first_name = 'Dan',
                last_name = 'Ackroyd',
                name = 'Dan Ackroyd',
                registry_id = 1,
                created_at = '2024-03-12T13:11:55.000000Z',
                updated_at = '2024-03-12T13:11:55.000000Z',
                user_group = 'USERS',
                consent_scrape = False,
                orc_id = '',
                unclaimed = 0,
                feed_source = '',
                public_opt_in = 0,
                organisation_id = 0,
                orcid_scanning = False,
                orcid_scanning_completed_at = '',
                is_delegate = 0,
                is_org_admin = 0,
                custodian_id = 56,
                custodian_user_id = 56,
                role = '',
                location = '',
                t_and_c_agreed = True,
                t_and_c_agreement_date = '2024-03-12 13:11:55',
                is_sro = False,
                invited_by = 56,
                status = 'registered',
                evaluation = '',
                identity = safepeopleregistry_api_sdk.models.identity.Identity(
                    id = 1, 
                    registry_id = 42, 
                    address_1 = '123 Example Street', 
                    address_2 = 'Suite 456', 
                    town = 'Example Town', 
                    county = 'Example County', 
                    country = 'UK', 
                    postcode = 'EX12 3AB', 
                    dob = 'Mon Jan 01 00:00:00 UTC 1990', 
                    idvt_success = 1, 
                    idvt_identification_number = 'ID12345', 
                    idvt_document_type = 'passport', 
                    idvt_document_number = '123456789', 
                    idvt_document_country = 'UK', 
                    idvt_document_valid_until = 'Tue Jan 01 00:00:00 UTC 2030', 
                    idvt_attempt_id = 'ATT12345', 
                    idvt_context_id = 'CTX12345', 
                    idvt_document_dob = 'Mon Jan 01 00:00:00 UTC 1990', 
                    idvt_context = 'Verification Context', 
                    idvt_completed_at = '2025-06-25T12:00Z', 
                    idvt_result_text = 'Verification successful', 
                    idvt_started_at = '2025-06-25T10:00Z', 
                    created_at = '2025-06-25T12:00Z', 
                    updated_at = '2025-06-25T12:00Z', 
                    deleted_at = '2025-06-25T12:00Z', )
            )
        else:
            return QueryQuery200ResponseDataUser(
        )
        """

    def testQueryQuery200ResponseDataUser(self):
        """Test QueryQuery200ResponseDataUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
