# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_get_project_users200_response_data_inner_registry_organisations_inner import ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner

class TestProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner(unittest.TestCase):
    """ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner:
        """Test ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner`
        """
        model = ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner()
        if include_optional:
            return ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner(
                id = 3,
                organisation_name = 'TANDY ENERGY LIMITED'
            )
        else:
            return ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner(
        )
        """

    def testProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner(self):
        """Test ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
