# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.notifications_get_notification_counts200_response import NotificationsGetNotificationCounts200Response

class TestNotificationsGetNotificationCounts200Response(unittest.TestCase):
    """NotificationsGetNotificationCounts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationsGetNotificationCounts200Response:
        """Test NotificationsGetNotificationCounts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationsGetNotificationCounts200Response`
        """
        model = NotificationsGetNotificationCounts200Response()
        if include_optional:
            return NotificationsGetNotificationCounts200Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.notifications_get_notification_counts_200_response_data.notificationsGetNotificationCounts_200_response_data(
                    total = 0, 
                    read = 0, 
                    unread = 0, )
            )
        else:
            return NotificationsGetNotificationCounts200Response(
        )
        """

    def testNotificationsGetNotificationCounts200Response(self):
        """Test NotificationsGetNotificationCounts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
