# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.webhooks_get_all_receivers200_response_data_inner_event_trigger import WebhooksGetAllReceivers200ResponseDataInnerEventTrigger

class TestWebhooksGetAllReceivers200ResponseDataInnerEventTrigger(unittest.TestCase):
    """WebhooksGetAllReceivers200ResponseDataInnerEventTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhooksGetAllReceivers200ResponseDataInnerEventTrigger:
        """Test WebhooksGetAllReceivers200ResponseDataInnerEventTrigger
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhooksGetAllReceivers200ResponseDataInnerEventTrigger`
        """
        model = WebhooksGetAllReceivers200ResponseDataInnerEventTrigger()
        if include_optional:
            return WebhooksGetAllReceivers200ResponseDataInnerEventTrigger(
                id = 1,
                name = 'user_created',
                description = 'Triggered when a new user is created'
            )
        else:
            return WebhooksGetAllReceivers200ResponseDataInnerEventTrigger(
        )
        """

    def testWebhooksGetAllReceivers200ResponseDataInnerEventTrigger(self):
        """Test WebhooksGetAllReceivers200ResponseDataInnerEventTrigger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
