# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.endorsement import Endorsement

class TestEndorsement(unittest.TestCase):
    """Endorsement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Endorsement:
        """Test Endorsement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Endorsement`
        """
        model = Endorsement()
        if include_optional:
            return Endorsement(
                id = 1,
                reported_by = 42,
                comment = 'This is a comment regarding the endorsement.',
                raised_against = 24,
                created_at = '2025-06-25T12:00Z',
                updated_at = '2025-06-25T12:00Z'
            )
        else:
            return Endorsement(
        )
        """

    def testEndorsement(self):
        """Test Endorsement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
