# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.accreditation_index_by_registry_id400_response import AccreditationIndexByRegistryId400Response

class TestAccreditationIndexByRegistryId400Response(unittest.TestCase):
    """AccreditationIndexByRegistryId400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccreditationIndexByRegistryId400Response:
        """Test AccreditationIndexByRegistryId400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccreditationIndexByRegistryId400Response`
        """
        model = AccreditationIndexByRegistryId400Response()
        if include_optional:
            return AccreditationIndexByRegistryId400Response(
                message = 'Invalid argument(s)'
            )
        else:
            return AccreditationIndexByRegistryId400Response(
        )
        """

    def testAccreditationIndexByRegistryId400Response(self):
        """Test AccreditationIndexByRegistryId400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
