# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.feature_index200_response import FeatureIndex200Response

class TestFeatureIndex200Response(unittest.TestCase):
    """FeatureIndex200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureIndex200Response:
        """Test FeatureIndex200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureIndex200Response`
        """
        model = FeatureIndex200Response()
        if include_optional:
            return FeatureIndex200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.feature_index_200_response_data.featureIndex_200_response_data(
                    id = 123, 
                    name = 'feature', 
                    scope = '\App\Model|User:1', 
                    value = True, 
                    description = 'description', 
                    created_at = '2024-02-04 12:00:00', 
                    updated_at = '2024-02-04 12:01:00', )
            )
        else:
            return FeatureIndex200Response(
        )
        """

    def testFeatureIndex200Response(self):
        """Test FeatureIndex200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
