# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_model_config_get_by_custodian_id200_response import CustodianModelConfigGetByCustodianID200Response

class TestCustodianModelConfigGetByCustodianID200Response(unittest.TestCase):
    """CustodianModelConfigGetByCustodianID200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianModelConfigGetByCustodianID200Response:
        """Test CustodianModelConfigGetByCustodianID200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianModelConfigGetByCustodianID200Response`
        """
        model = CustodianModelConfigGetByCustodianID200Response()
        if include_optional:
            return CustodianModelConfigGetByCustodianID200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.custodian_model_config.CustodianModelConfig(
                    id = 1, 
                    created_at = '2023-10-10T15:03:00Z', 
                    updated_at = '2023-10-10T18:03:00Z', 
                    entity_model_id = 1, 
                    active = True, 
                    custodian_id = 12, )
            )
        else:
            return CustodianModelConfigGetByCustodianID200Response(
        )
        """

    def testCustodianModelConfigGetByCustodianID200Response(self):
        """Test CustodianModelConfigGetByCustodianID200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
