# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.validation_log_with_comments_index404_response import ValidationLogWithCommentsIndex404Response

class TestValidationLogWithCommentsIndex404Response(unittest.TestCase):
    """ValidationLogWithCommentsIndex404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationLogWithCommentsIndex404Response:
        """Test ValidationLogWithCommentsIndex404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationLogWithCommentsIndex404Response`
        """
        model = ValidationLogWithCommentsIndex404Response()
        if include_optional:
            return ValidationLogWithCommentsIndex404Response(
                message = 'Validation log not found'
            )
        else:
            return ValidationLogWithCommentsIndex404Response(
        )
        """

    def testValidationLogWithCommentsIndex404Response(self):
        """Test ValidationLogWithCommentsIndex404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
