# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.validation_log_comments_destroy200_response import ValidationLogCommentsDestroy200Response

class TestValidationLogCommentsDestroy200Response(unittest.TestCase):
    """ValidationLogCommentsDestroy200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationLogCommentsDestroy200Response:
        """Test ValidationLogCommentsDestroy200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationLogCommentsDestroy200Response`
        """
        model = ValidationLogCommentsDestroy200Response()
        if include_optional:
            return ValidationLogCommentsDestroy200Response(
                message = 'Comment deleted successfully'
            )
        else:
            return ValidationLogCommentsDestroy200Response(
        )
        """

    def testValidationLogCommentsDestroy200Response(self):
        """Test ValidationLogCommentsDestroy200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
