# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.affiliation_destroy200_response import AffiliationDestroy200Response

class TestAffiliationDestroy200Response(unittest.TestCase):
    """AffiliationDestroy200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliationDestroy200Response:
        """Test AffiliationDestroy200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliationDestroy200Response`
        """
        model = AffiliationDestroy200Response()
        if include_optional:
            return AffiliationDestroy200Response(
                message = 'success'
            )
        else:
            return AffiliationDestroy200Response(
        )
        """

    def testAffiliationDestroy200Response(self):
        """Test AffiliationDestroy200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
