# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisations_get_registries404_response import OrganisationsGetRegistries404Response

class TestOrganisationsGetRegistries404Response(unittest.TestCase):
    """OrganisationsGetRegistries404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationsGetRegistries404Response:
        """Test OrganisationsGetRegistries404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationsGetRegistries404Response`
        """
        model = OrganisationsGetRegistries404Response()
        if include_optional:
            return OrganisationsGetRegistries404Response(
                message = 'No registries found for this organisation'
            )
        else:
            return OrganisationsGetRegistries404Response(
        )
        """

    def testOrganisationsGetRegistries404Response(self):
        """Test OrganisationsGetRegistries404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
