# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.custodian_users_api import CustodianUsersApi


class TestCustodianUsersApi(unittest.TestCase):
    """CustodianUsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustodianUsersApi()

    def tearDown(self) -> None:
        pass

    def test_custodian_users_index(self) -> None:
        """Test case for custodian_users_index

        Return a list of Custodian Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
