# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_make_primary_contact200_response_data_inner_registry import ProjectMakePrimaryContact200ResponseDataInnerRegistry

class TestProjectMakePrimaryContact200ResponseDataInnerRegistry(unittest.TestCase):
    """ProjectMakePrimaryContact200ResponseDataInnerRegistry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectMakePrimaryContact200ResponseDataInnerRegistry:
        """Test ProjectMakePrimaryContact200ResponseDataInnerRegistry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectMakePrimaryContact200ResponseDataInnerRegistry`
        """
        model = ProjectMakePrimaryContact200ResponseDataInnerRegistry()
        if include_optional:
            return ProjectMakePrimaryContact200ResponseDataInnerRegistry(
                id = 9,
                created_at = '2024-12-03T10:17:08Z',
                updated_at = '2024-12-03T10:17:08Z',
                verified = False,
                user = safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_registry_user.projectGetProjectUsers_200_response_data_inner_registry_user(
                    id = 18, 
                    first_name = 'Tobacco', 
                    last_name = 'Dave', 
                    email = 'tobacco.dave@dodgydomain.com', 
                    registry_id = 9, 
                    created_at = '2024-12-03T10:17:06Z', 
                    updated_at = '2024-12-03T10:17:08Z', 
                    user_group = 'USERS', 
                    consent_scrape = False, 
                    public_opt_in = False, )
            )
        else:
            return ProjectMakePrimaryContact200ResponseDataInnerRegistry(
        )
        """

    def testProjectMakePrimaryContact200ResponseDataInnerRegistry(self):
        """Test ProjectMakePrimaryContact200ResponseDataInnerRegistry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
