# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.sector_api import SectorApi


class TestSectorApi(unittest.TestCase):
    """SectorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SectorApi()

    def tearDown(self) -> None:
        pass

    def test_sector_destroy(self) -> None:
        """Test case for sector_destroy

        Delete a sector
        """
        pass

    def test_sector_index(self) -> None:
        """Test case for sector_index

        Get a list of sectors
        """
        pass

    def test_sector_show(self) -> None:
        """Test case for sector_show

        Get a specific sector by ID
        """
        pass

    def test_sector_store(self) -> None:
        """Test case for sector_store

        Create a new sector
        """
        pass

    def test_sector_update(self) -> None:
        """Test case for sector_update

        Update an existing sector
        """
        pass


if __name__ == '__main__':
    unittest.main()
