# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.webhooks_create_receiver201_response import WebhooksCreateReceiver201Response

class TestWebhooksCreateReceiver201Response(unittest.TestCase):
    """WebhooksCreateReceiver201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhooksCreateReceiver201Response:
        """Test WebhooksCreateReceiver201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhooksCreateReceiver201Response`
        """
        model = WebhooksCreateReceiver201Response()
        if include_optional:
            return WebhooksCreateReceiver201Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.webhooks_create_receiver_201_response_data.webhooksCreateReceiver_201_response_data(
                    id = 1, 
                    custodian_id = 1, 
                    url = 'https://example.com/webhook', 
                    webhook_event = 1, 
                    created_at = '2023-06-07T12:00Z', 
                    updated_at = '2023-06-07T12:00Z', )
            )
        else:
            return WebhooksCreateReceiver201Response(
        )
        """

    def testWebhooksCreateReceiver201Response(self):
        """Test WebhooksCreateReceiver201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
