# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_projects_delete(self) -> None:
        """Test case for projects_delete

        ProjectHasUser@delete
        """
        pass

    def test_projects_get_validated_projects(self) -> None:
        """Test case for projects_get_validated_projects

        Project@getValidatedProjects
        """
        pass


if __name__ == '__main__':
    unittest.main()
