# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_get_project_by_id_and_user_id404_response import ProjectGetProjectByIdAndUserId404Response

class TestProjectGetProjectByIdAndUserId404Response(unittest.TestCase):
    """ProjectGetProjectByIdAndUserId404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGetProjectByIdAndUserId404Response:
        """Test ProjectGetProjectByIdAndUserId404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGetProjectByIdAndUserId404Response`
        """
        model = ProjectGetProjectByIdAndUserId404Response()
        if include_optional:
            return ProjectGetProjectByIdAndUserId404Response(
                message = 'Project not found'
            )
        else:
            return ProjectGetProjectByIdAndUserId404Response(
        )
        """

    def testProjectGetProjectByIdAndUserId404Response(self):
        """Test ProjectGetProjectByIdAndUserId404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
