# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_get_project_users200_response import ProjectGetProjectUsers200Response

class TestProjectGetProjectUsers200Response(unittest.TestCase):
    """ProjectGetProjectUsers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGetProjectUsers200Response:
        """Test ProjectGetProjectUsers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGetProjectUsers200Response`
        """
        model = ProjectGetProjectUsers200Response()
        if include_optional:
            return ProjectGetProjectUsers200Response(
                message = 'success',
                data = [
                    safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner.projectGetProjectUsers_200_response_data_inner(
                        project_id = 1, 
                        user_digital_ident = '$2y$12$IJ2LFUartH4N9xKSfxyL5ee5wdJC59aqKx180/72J3oonpw0JFiD2', 
                        registry = safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_registry.projectGetProjectUsers_200_response_data_inner_registry(
                            id = 9, 
                            created_at = '2024-12-03T10:17:08Z', 
                            updated_at = '2024-12-03T10:17:08Z', 
                            verified = False, 
                            user = safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_registry_user.projectGetProjectUsers_200_response_data_inner_registry_user(
                                id = 18, 
                                first_name = 'Tobacco', 
                                last_name = 'Dave', 
                                email = 'tobacco.dave@dodgydomain.com', 
                                registry_id = 9, 
                                created_at = '2024-12-03T10:17:06Z', 
                                updated_at = '2024-12-03T10:17:08Z', 
                                user_group = 'USERS', 
                                consent_scrape = False, 
                                public_opt_in = False, ), 
                            organisations = [
                                safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_registry_organisations_inner.projectGetProjectUsers_200_response_data_inner_registry_organisations_inner(
                                    id = 3, 
                                    organisation_name = 'TANDY ENERGY LIMITED', )
                                ], 
                            affiliation = safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_registry_affiliation.projectGetProjectUsers_200_response_data_inner_registry_affiliation(
                                relationship = 'employee', 
                                from = '25/01/1999', 
                                to = '01/12/2010', 
                                department = 'Research & Development', 
                                role = 'Principal Investigator (PI)', 
                                email = 'professional.email@email.com', 
                                ror = '0hgyje84', ), ), 
                        role = safepeopleregistry_api_sdk.models.project_get_project_users_200_response_data_inner_role.projectGetProjectUsers_200_response_data_inner_role(
                            id = 1, 
                            name = 'Principal Investigator (PI)', ), )
                    ]
            )
        else:
            return ProjectGetProjectUsers200Response(
        )
        """

    def testProjectGetProjectUsers200Response(self):
        """Test ProjectGetProjectUsers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
