# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_user_show200_response import CustodianUserShow200Response

class TestCustodianUserShow200Response(unittest.TestCase):
    """CustodianUserShow200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianUserShow200Response:
        """Test CustodianUserShow200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianUserShow200Response`
        """
        model = CustodianUserShow200Response()
        if include_optional:
            return CustodianUserShow200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.custodian_user.Custodian User(
                    id = 1, 
                    custodian_id = 1, 
                    created_at = '2023-10-10T15:03:00Z', 
                    updated_at = '2023-10-10T15:03:00Z', 
                    first_name = 'John', 
                    last_name = 'Smith', 
                    email = 'First name', ),
                user_permissions = [
                    safepeopleregistry_api_sdk.models.custodian_user_show_200_response_user_permissions_inner.custodianUserShow_200_response_user_permissions_inner(
                        custodian_user_id = 1, 
                        permission_id = 10, 
                        permission = safepeopleregistry_api_sdk.models.permission.Permission(
                            id = 1, 
                            name = 'View Reports', 
                            enabled = True, 
                            description = 'Allows viewing of reports', 
                            created_at = '2025-06-25T12:00Z', 
                            updated_at = '2025-06-25T12:00Z', ), )
                    ]
            )
        else:
            return CustodianUserShow200Response(
        )
        """

    def testCustodianUserShow200Response(self):
        """Test CustodianUserShow200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
