# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.permission_api import PermissionApi


class TestPermissionApi(unittest.TestCase):
    """PermissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermissionApi()

    def tearDown(self) -> None:
        pass

    def test_permission_destroy(self) -> None:
        """Test case for permission_destroy

        Permission@destroy
        """
        pass

    def test_permission_index(self) -> None:
        """Test case for permission_index

        Permission@index
        """
        pass

    def test_permission_show(self) -> None:
        """Test case for permission_show

        Permission@show
        """
        pass

    def test_permission_store(self) -> None:
        """Test case for permission_store

        Permission@store
        """
        pass

    def test_permission_update(self) -> None:
        """Test case for permission_update

        Permission@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
