# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation200_response import AffiliationsGetOrganisationAffiliation200Response

class TestAffiliationsGetOrganisationAffiliation200Response(unittest.TestCase):
    """AffiliationsGetOrganisationAffiliation200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliationsGetOrganisationAffiliation200Response:
        """Test AffiliationsGetOrganisationAffiliation200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliationsGetOrganisationAffiliation200Response`
        """
        model = AffiliationsGetOrganisationAffiliation200Response()
        if include_optional:
            return AffiliationsGetOrganisationAffiliation200Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data.affiliationsGetOrganisationAffiliation_200_response_data(
                    id = 123, 
                    registry_id = 1, 
                    organisation_id = 100, 
                    model_state_id = 2, 
                    model_state = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_model_state.affiliationsGetOrganisationAffiliation_200_response_data_model_state(
                        id = 2, 
                        state_id = 5, 
                        state = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_model_state_state.affiliationsGetOrganisationAffiliation_200_response_data_model_state_state(
                            id = 5, 
                            name = 'Approved', ), ), 
                    organisation = safepeopleregistry_api_sdk.models.affiliations_get_organisation_affiliation_200_response_data_organisation.affiliationsGetOrganisationAffiliation_200_response_data_organisation(
                        id = 100, 
                        organisation_name = 'Example Org', 
                        unclaimed = False, 
                        lead_applicant_email = 'lead@example.org', ), )
            )
        else:
            return AffiliationsGetOrganisationAffiliation200Response(
        )
        """

    def testAffiliationsGetOrganisationAffiliation200Response(self):
        """Test AffiliationsGetOrganisationAffiliation200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
