# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisation_get_projects200_response_data import OrganisationGetProjects200ResponseData

class TestOrganisationGetProjects200ResponseData(unittest.TestCase):
    """OrganisationGetProjects200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationGetProjects200ResponseData:
        """Test OrganisationGetProjects200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationGetProjects200ResponseData`
        """
        model = OrganisationGetProjects200ResponseData()
        if include_optional:
            return OrganisationGetProjects200ResponseData(
                id = 123,
                created_at = '2024-02-04 12:00:00',
                updated_at = '2024-02-04 12:01:00',
                registry_id = 1,
                name = 'My First Research Project',
                public_benefit = 'A public benefit statement',
                runs_to = '2026-02-04',
                affiliate_id = 2
            )
        else:
            return OrganisationGetProjects200ResponseData(
        )
        """

    def testOrganisationGetProjects200ResponseData(self):
        """Test OrganisationGetProjects200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
