# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_add_project201_response import CustodianAddProject201Response

class TestCustodianAddProject201Response(unittest.TestCase):
    """CustodianAddProject201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianAddProject201Response:
        """Test CustodianAddProject201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianAddProject201Response`
        """
        model = CustodianAddProject201Response()
        if include_optional:
            return CustodianAddProject201Response(
                message = 'success',
                data = 1
            )
        else:
            return CustodianAddProject201Response(
        )
        """

    def testCustodianAddProject201Response(self):
        """Test CustodianAddProject201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
