# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodians_get_rules200_response_data_inner import CustodiansGetRules200ResponseDataInner

class TestCustodiansGetRules200ResponseDataInner(unittest.TestCase):
    """CustodiansGetRules200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodiansGetRules200ResponseDataInner:
        """Test CustodiansGetRules200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodiansGetRules200ResponseDataInner`
        """
        model = CustodiansGetRules200ResponseDataInner()
        if include_optional:
            return CustodiansGetRules200ResponseDataInner(
                id = 2,
                name = 'userLocation',
                title = 'User location',
                description = 'A User should be located in a country which adheres to equivalent data protection law.'
            )
        else:
            return CustodiansGetRules200ResponseDataInner(
        )
        """

    def testCustodiansGetRules200ResponseDataInner(self):
        """Test CustodiansGetRules200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
