# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.files_show200_response import FilesShow200Response

class TestFilesShow200Response(unittest.TestCase):
    """FilesShow200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilesShow200Response:
        """Test FilesShow200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilesShow200Response`
        """
        model = FilesShow200Response()
        if include_optional:
            return FilesShow200Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.files_show_200_response_data.filesShow_200_response_data(
                    id = 1, 
                    name = 'users.csv', 
                    path = '1739297394_users.csv', 
                    type = 'RESEARCHERS_LIST', 
                    status = 'failed', )
            )
        else:
            return FilesShow200Response(
        )
        """

    def testFilesShow200Response(self):
        """Test FilesShow200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
