# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_get_all_users_flag_project_by_user_id200_response_data_inner import ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner

class TestProjectGetAllUsersFlagProjectByUserId200ResponseDataInner(unittest.TestCase):
    """ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner:
        """Test ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner`
        """
        model = ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner()
        if include_optional:
            return ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner(
                id = 1,
                project_user_id = 1,
                user_id = 14,
                registry_id = 5,
                first_name = 'Harold',
                last_name = 'Ramis',
                professional_email = 'nlindgren@hotmail.com',
                affiliation_id = 6,
                organisation_name = 'TANDY ENERGY LIMITED',
                role = 1
            )
        else:
            return ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner(
        )
        """

    def testProjectGetAllUsersFlagProjectByUserId200ResponseDataInner(self):
        """Test ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
