# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.validation_check import ValidationCheck

class TestValidationCheck(unittest.TestCase):
    """ValidationCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationCheck:
        """Test ValidationCheck
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationCheck`
        """
        model = ValidationCheck()
        if include_optional:
            return ValidationCheck(
                id = 1,
                name = 'Check format',
                description = 'Ensures proper formatting of input',
                applies_to = 'user',
                enabled = True,
                created_at = '2024-01-01T00:00Z',
                updated_at = '2024-01-01T00:00Z',
                custodian_id = 1
            )
        else:
            return ValidationCheck(
                name = 'Check format',
                description = 'Ensures proper formatting of input',
                applies_to = 'user',
        )
        """

    def testValidationCheck(self):
        """Test ValidationCheck"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
