# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.feature_api import FeatureApi


class TestFeatureApi(unittest.TestCase):
    """FeatureApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeatureApi()

    def tearDown(self) -> None:
        pass

    def test_feature_index(self) -> None:
        """Test case for feature_index

        Feature@index
        """
        pass


if __name__ == '__main__':
    unittest.main()
