# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.affiliation_api import AffiliationApi


class TestAffiliationApi(unittest.TestCase):
    """AffiliationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AffiliationApi()

    def tearDown(self) -> None:
        pass

    def test_affiliation_destroy(self) -> None:
        """Test case for affiliation_destroy

        Affiliation@destroy
        """
        pass


if __name__ == '__main__':
    unittest.main()
