# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_has_organisation_show500_response import ProjectHasOrganisationShow500Response

class TestProjectHasOrganisationShow500Response(unittest.TestCase):
    """ProjectHasOrganisationShow500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectHasOrganisationShow500Response:
        """Test ProjectHasOrganisationShow500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectHasOrganisationShow500Response`
        """
        model = ProjectHasOrganisationShow500Response()
        if include_optional:
            return ProjectHasOrganisationShow500Response(
                message = 'An error occurred'
            )
        else:
            return ProjectHasOrganisationShow500Response(
        )
        """

    def testProjectHasOrganisationShow500Response(self):
        """Test ProjectHasOrganisationShow500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
