# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.professional_registrations_api import ProfessionalRegistrationsApi


class TestProfessionalRegistrationsApi(unittest.TestCase):
    """ProfessionalRegistrationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfessionalRegistrationsApi()

    def tearDown(self) -> None:
        pass

    def test_professional_registrations_update(self) -> None:
        """Test case for professional_registrations_update

        Professional Registrations@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
