# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_user_update201_response import CustodianUserUpdate201Response

class TestCustodianUserUpdate201Response(unittest.TestCase):
    """CustodianUserUpdate201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianUserUpdate201Response:
        """Test CustodianUserUpdate201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianUserUpdate201Response`
        """
        model = CustodianUserUpdate201Response()
        if include_optional:
            return CustodianUserUpdate201Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.custodian_user.Custodian User(
                    id = 1, 
                    custodian_id = 1, 
                    created_at = '2023-10-10T15:03:00Z', 
                    updated_at = '2023-10-10T15:03:00Z', 
                    first_name = 'John', 
                    last_name = 'Smith', 
                    email = 'First name', )
            )
        else:
            return CustodianUserUpdate201Response(
        )
        """

    def testCustodianUserUpdate201Response(self):
        """Test CustodianUserUpdate201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
