# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.ons_submission_api import ONSSubmissionApi


class TestONSSubmissionApi(unittest.TestCase):
    """ONSSubmissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ONSSubmissionApi()

    def tearDown(self) -> None:
        pass

    def test_o_ns_submission_receive_csv(self) -> None:
        """Test case for o_ns_submission_receive_csv

        Upload a CSV file for ONS submission
        """
        pass


if __name__ == '__main__':
    unittest.main()
