# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.training_api import TrainingApi


class TestTrainingApi(unittest.TestCase):
    """TrainingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrainingApi()

    def tearDown(self) -> None:
        pass

    def test_training_index(self) -> None:
        """Test case for training_index

        Training@index
        """
        pass

    def test_training_index_by_registry_id(self) -> None:
        """Test case for training_index_by_registry_id

        Training@show
        """
        pass

    def test_training_show(self) -> None:
        """Test case for training_show

        Training@show
        """
        pass

    def test_training_store(self) -> None:
        """Test case for training_store

        Training@store
        """
        pass

    def test_training_update(self) -> None:
        """Test case for training_update

        Training@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
