# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.validation_log_comments_api import ValidationLogCommentsApi


class TestValidationLogCommentsApi(unittest.TestCase):
    """ValidationLogCommentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationLogCommentsApi()

    def tearDown(self) -> None:
        pass

    def test_validation_log_comments_comments(self) -> None:
        """Test case for validation_log_comments_comments

        Get all comments for a Validation Log
        """
        pass

    def test_validation_log_comments_destroy(self) -> None:
        """Test case for validation_log_comments_destroy

        Delete a validation log comment
        """
        pass

    def test_validation_log_comments_show(self) -> None:
        """Test case for validation_log_comments_show

        Get a single validation log comment
        """
        pass

    def test_validation_log_comments_store(self) -> None:
        """Test case for validation_log_comments_store

        Create a new validation log comment
        """
        pass

    def test_validation_log_comments_update(self) -> None:
        """Test case for validation_log_comments_update

        Update a validation log comment
        """
        pass


if __name__ == '__main__':
    unittest.main()
