# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_update_all_project_users_request_users_inner import ProjectUpdateAllProjectUsersRequestUsersInner

class TestProjectUpdateAllProjectUsersRequestUsersInner(unittest.TestCase):
    """ProjectUpdateAllProjectUsersRequestUsersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectUpdateAllProjectUsersRequestUsersInner:
        """Test ProjectUpdateAllProjectUsersRequestUsersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectUpdateAllProjectUsersRequestUsersInner`
        """
        model = ProjectUpdateAllProjectUsersRequestUsersInner()
        if include_optional:
            return ProjectUpdateAllProjectUsersRequestUsersInner(
                registry_id = 5,
                affiliation_id = 6,
                project_user_id = 1,
                primary_contact = False,
                role = safepeopleregistry_api_sdk.models.project_update_all_project_users_request_users_inner_role.projectUpdateAllProjectUsers_request_users_inner_role(
                    id = 1, )
            )
        else:
            return ProjectUpdateAllProjectUsersRequestUsersInner(
        )
        """

    def testProjectUpdateAllProjectUsersRequestUsersInner(self):
        """Test ProjectUpdateAllProjectUsersRequestUsersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
