# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.infringement_store201_response import InfringementStore201Response

class TestInfringementStore201Response(unittest.TestCase):
    """InfringementStore201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfringementStore201Response:
        """Test InfringementStore201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfringementStore201Response`
        """
        model = InfringementStore201Response()
        if include_optional:
            return InfringementStore201Response(
                message = 'success',
                data = 123
            )
        else:
            return InfringementStore201Response(
        )
        """

    def testInfringementStore201Response(self):
        """Test InfringementStore201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
