# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_store_request import ProjectStoreRequest

class TestProjectStoreRequest(unittest.TestCase):
    """ProjectStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectStoreRequest:
        """Test ProjectStoreRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectStoreRequest`
        """
        model = ProjectStoreRequest()
        if include_optional:
            return ProjectStoreRequest(
                registry_id = 1,
                name = 'My First Research Project',
                public_benefit = 'A public benefit statement',
                runs_to = '2026-02-04'
            )
        else:
            return ProjectStoreRequest(
        )
        """

    def testProjectStoreRequest(self):
        """Test ProjectStoreRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
