# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_project_organisations_get_workflow_states200_response import CustodianProjectOrganisationsGetWorkflowStates200Response

class TestCustodianProjectOrganisationsGetWorkflowStates200Response(unittest.TestCase):
    """CustodianProjectOrganisationsGetWorkflowStates200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianProjectOrganisationsGetWorkflowStates200Response:
        """Test CustodianProjectOrganisationsGetWorkflowStates200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianProjectOrganisationsGetWorkflowStates200Response`
        """
        model = CustodianProjectOrganisationsGetWorkflowStates200Response()
        if include_optional:
            return CustodianProjectOrganisationsGetWorkflowStates200Response(
                message = 'success',
                data = [
                    'pending'
                    ]
            )
        else:
            return CustodianProjectOrganisationsGetWorkflowStates200Response(
        )
        """

    def testCustodianProjectOrganisationsGetWorkflowStates200Response(self):
        """Test CustodianProjectOrganisationsGetWorkflowStates200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
