# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_has_role import ProjectHasRole

class TestProjectHasRole(unittest.TestCase):
    """ProjectHasRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectHasRole:
        """Test ProjectHasRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectHasRole`
        """
        model = ProjectHasRole()
        if include_optional:
            return ProjectHasRole(
                project_id = 42,
                project_role_id = 24
            )
        else:
            return ProjectHasRole(
        )
        """

    def testProjectHasRole(self):
        """Test ProjectHasRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
