# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.training_show200_response import TrainingShow200Response

class TestTrainingShow200Response(unittest.TestCase):
    """TrainingShow200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrainingShow200Response:
        """Test TrainingShow200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrainingShow200Response`
        """
        model = TrainingShow200Response()
        if include_optional:
            return TrainingShow200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.training.Training(
                    id = 123, 
                    created_at = '2024-02-04 12:00:00', 
                    updated_at = '2024-02-04 12:01:00', 
                    registry_id = 1, 
                    provider = 'ONS', 
                    awarded_at = '2024-02-04', 
                    expires_at = '2026-02-04', 
                    expires_in_years = 2, 
                    training_name = 'Safe Researcher Training', 
                    pro_registration = 1, )
            )
        else:
            return TrainingShow200Response(
        )
        """

    def testTrainingShow200Response(self):
        """Test TrainingShow200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
