# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.history_index200_response import HistoryIndex200Response

class TestHistoryIndex200Response(unittest.TestCase):
    """HistoryIndex200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HistoryIndex200Response:
        """Test HistoryIndex200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HistoryIndex200Response`
        """
        model = HistoryIndex200Response()
        if include_optional:
            return HistoryIndex200Response(
                message = '',
                data = safepeopleregistry_api_sdk.models.history_index_200_response_data.historyIndex_200_response_data(
                    id = 123, 
                    created_at = '2024-02-04 12:00:00', 
                    updated_at = '2024-02-04 12:01:00', 
                    endorsement_id = 213, 
                    infringement_id = 12, 
                    project_id = 2, 
                    access_key_id = 2, 
                    custodian_identifier = 'ABCD1234FGHI56789', )
            )
        else:
            return HistoryIndex200Response(
        )
        """

    def testHistoryIndex200Response(self):
        """Test HistoryIndex200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
