# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.project_get_project_by_id_and_user_id200_response import ProjectGetProjectByIdAndUserId200Response

class TestProjectGetProjectByIdAndUserId200Response(unittest.TestCase):
    """ProjectGetProjectByIdAndUserId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGetProjectByIdAndUserId200Response:
        """Test ProjectGetProjectByIdAndUserId200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGetProjectByIdAndUserId200Response`
        """
        model = ProjectGetProjectByIdAndUserId200Response()
        if include_optional:
            return ProjectGetProjectByIdAndUserId200Response(
                message = 'success',
                data = [
                    safepeopleregistry_api_sdk.models.project.Project(
                        id = 1, 
                        title = 'Project name', 
                        unique_id = '89AItHDuaqXsfgqOA85d', 
                        lay_summary = 'This study aims to evaluate how digital mental health interventions (such as mobile apps for meditation, cognitive behavioral therapy, and mental health tracking) affect the mental health and well-being of young adults aged 18-30.', 
                        public_benefit = 'The findings from this research could lead to improved digital health interventions tailored to the mental health needs of young adults.', 
                        request_category_type = 'Health and Social Research', 
                        technical_summary = 'This project involves analyzing anonymized, aggregated data from digital health applications used by young adults.', 
                        other_approval_commitees = 'This project requires approval from:  University Institutional Review Board (IRB) to ensure ethical considerations are met. Data Access Committee (DAC) from the app providers to secure permissions for using anonymized, aggregated data.', 
                        start_date = '2023-10-10T15:03:00Z', 
                        end_date = '2024-10-10T15:03:00Z', )
                    ]
            )
        else:
            return ProjectGetProjectByIdAndUserId200Response(
        )
        """

    def testProjectGetProjectByIdAndUserId200Response(self):
        """Test ProjectGetProjectByIdAndUserId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
