# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.accreditation_api import AccreditationApi


class TestAccreditationApi(unittest.TestCase):
    """AccreditationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccreditationApi()

    def tearDown(self) -> None:
        pass

    def test_accreditation_index_by_registry_id(self) -> None:
        """Test case for accreditation_index_by_registry_id

        Get accreditations by registry ID
        """
        pass

    def test_accreditation_store_by_registry_id(self) -> None:
        """Test case for accreditation_store_by_registry_id

        Create accreditation for a registry
        """
        pass

    def test_accreditation_update_by_registry_id(self) -> None:
        """Test case for accreditation_update_by_registry_id

        Update accreditation for a registry
        """
        pass


if __name__ == '__main__':
    unittest.main()
