# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.query_query200_response import QueryQuery200Response

class TestQueryQuery200Response(unittest.TestCase):
    """QueryQuery200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryQuery200Response:
        """Test QueryQuery200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryQuery200Response`
        """
        model = QueryQuery200Response()
        if include_optional:
            return QueryQuery200Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.query_query_200_response_data.queryQuery_200_response_data(
                    user = safepeopleregistry_api_sdk.models.query_query_200_response_data_user.queryQuery_200_response_data_user(
                        id = 10, 
                        first_name = 'Dan', 
                        last_name = 'Ackroyd', 
                        name = 'Dan Ackroyd', 
                        registry_id = 1, 
                        created_at = '2024-03-12T13:11:55.000000Z', 
                        updated_at = '2024-03-12T13:11:55.000000Z', 
                        user_group = 'USERS', 
                        consent_scrape = False, 
                        orc_id = '', 
                        unclaimed = 0, 
                        feed_source = '', 
                        public_opt_in = 0, 
                        organisation_id = 0, 
                        orcid_scanning = False, 
                        orcid_scanning_completed_at = '', 
                        is_delegate = 0, 
                        is_org_admin = 0, 
                        custodian_id = 56, 
                        custodian_user_id = 56, 
                        role = '', 
                        location = '', 
                        t_and_c_agreed = True, 
                        t_and_c_agreement_date = '2024-03-12 13:11:55', 
                        is_sro = False, 
                        invited_by = 56, 
                        status = 'registered', 
                        evaluation = '', 
                        identity = null, ), 
                    registry = safepeopleregistry_api_sdk.models.query_query_200_response_data_registry.queryQuery_200_response_data_registry(), 
                    projects = [
                        safepeopleregistry_api_sdk.models.query_query_200_response_data_projects_inner.queryQuery_200_response_data_projects_inner(
                            project_id = 1, 
                            project_title = 'Project Title', 
                            project_user_validation_status = 'ValidationComplete', )
                        ], )
            )
        else:
            return QueryQuery200Response(
        )
        """

    def testQueryQuery200Response(self):
        """Test QueryQuery200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
