# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.users_store201_response import UsersStore201Response

class TestUsersStore201Response(unittest.TestCase):
    """UsersStore201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersStore201Response:
        """Test UsersStore201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersStore201Response`
        """
        model = UsersStore201Response()
        if include_optional:
            return UsersStore201Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.users_store_201_response_data.usersStore_201_response_data(
                    id = 123, 
                    created_at = '2024-02-04 12:00:00', 
                    updated_at = '2024-02-04 12:01:00', 
                    first_name = 'A', 
                    last_name = 'Researcher', 
                    email = 'person@somewhere.com', 
                    email_verified_at = '2024-02-04 12:00:00', 
                    consent_scrape = True, 
                    public_opt_in = True, 
                    declaration_signed = True, 
                    organisation_id = 123, 
                    orcid_scanning = 1, 
                    orcid_scanning_completed_at = '2024-02-04 12:01:00', 
                    status = 'registered', 
                    uksa_registered = True, 
                    is_sro = False, )
            )
        else:
            return UsersStore201Response(
        )
        """

    def testUsersStore201Response(self):
        """Test UsersStore201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
