# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.validation_log_comment import ValidationLogComment

class TestValidationLogComment(unittest.TestCase):
    """ValidationLogComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationLogComment:
        """Test ValidationLogComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationLogComment`
        """
        model = ValidationLogComment()
        if include_optional:
            return ValidationLogComment(
                id = 1,
                validation_log_id = 1,
                user_id = 1,
                comment = 'This validation needs further review.',
                created_at = '2023-10-10T15:43Z',
                updated_at = '2023-10-10T16:00Z'
            )
        else:
            return ValidationLogComment(
        )
        """

    def testValidationLogComment(self):
        """Test ValidationLogComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
