# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_notifications_get_notification_counts(self) -> None:
        """Test case for notifications_get_notification_counts

        Get notification counts for a specific user
        """
        pass

    def test_notifications_get_user_notifications(self) -> None:
        """Test case for notifications_get_user_notifications

        Get notifications for a specific user
        """
        pass

    def test_notifications_mark_user_notification_as_read(self) -> None:
        """Test case for notifications_mark_user_notification_as_read

        Mark a specific notification as read
        """
        pass

    def test_notifications_mark_user_notification_as_unread(self) -> None:
        """Test case for notifications_mark_user_notification_as_unread

        Mark a specific notification as unread
        """
        pass

    def test_notifications_mark_user_notifications_as_read(self) -> None:
        """Test case for notifications_mark_user_notifications_as_read

        Mark all notifications as read for a specific user
        """
        pass


if __name__ == '__main__':
    unittest.main()
