# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.identity_api import IdentityApi


class TestIdentityApi(unittest.TestCase):
    """IdentityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentityApi()

    def tearDown(self) -> None:
        pass

    def test_identity_destroy(self) -> None:
        """Test case for identity_destroy

        Identity@destroy
        """
        pass

    def test_identity_index(self) -> None:
        """Test case for identity_index

        Identity@index
        """
        pass

    def test_identity_show(self) -> None:
        """Test case for identity_show

        Identity@show
        """
        pass

    def test_identity_store(self) -> None:
        """Test case for identity_store

        Identity@store
        """
        pass

    def test_identity_update(self) -> None:
        """Test case for identity_update

        Identity@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
