# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.validation_logs_update200_response import ValidationLogsUpdate200Response

class TestValidationLogsUpdate200Response(unittest.TestCase):
    """ValidationLogsUpdate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationLogsUpdate200Response:
        """Test ValidationLogsUpdate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationLogsUpdate200Response`
        """
        model = ValidationLogsUpdate200Response()
        if include_optional:
            return ValidationLogsUpdate200Response(
                message = 'Action status updated successfully',
                data = safepeopleregistry_api_sdk.models.validation_log.Validation Log(
                    id = 1, 
                    entity_type = 'App\\Models\\Custodian', 
                    entity_id = 1, 
                    secondary_entity_type = 'App\\Models\\Project', 
                    secondary_entity_id = 2, 
                    tertiary_entity_type = 'App\\Models\\Registry', 
                    tertiary_entity_id = 3, 
                    name = 'Validation Check 1', 
                    completed_at = '2023-10-10T15:43Z', 
                    manually_confirmed = True, )
            )
        else:
            return ValidationLogsUpdate200Response(
        )
        """

    def testValidationLogsUpdate200Response(self):
        """Test ValidationLogsUpdate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
