# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.api.history_api import HistoryApi


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoryApi()

    def tearDown(self) -> None:
        pass

    def test_history_index(self) -> None:
        """Test case for history_index

        History@index
        """
        pass

    def test_history_show(self) -> None:
        """Test case for history_show

        History@show
        """
        pass

    def test_history_store(self) -> None:
        """Test case for history_store

        History@store
        """
        pass


if __name__ == '__main__':
    unittest.main()
