# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.accreditation_index_by_registry_id200_response import AccreditationIndexByRegistryId200Response

class TestAccreditationIndexByRegistryId200Response(unittest.TestCase):
    """AccreditationIndexByRegistryId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccreditationIndexByRegistryId200Response:
        """Test AccreditationIndexByRegistryId200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccreditationIndexByRegistryId200Response`
        """
        model = AccreditationIndexByRegistryId200Response()
        if include_optional:
            return AccreditationIndexByRegistryId200Response(
                message = 'success',
                data = [
                    safepeopleregistry_api_sdk.models.accreditation.Accreditation(
                        id = 1, 
                        associated_organisation_name = 'University of Example', 
                        id_string = '123456', 
                        issue_date = 'Sun Jan 01 00:00:00 UTC 2023', 
                        expiry_date = 'Thu Jun 25 00:00:00 UTC 2026', 
                        created_at = '2025-06-25T12:00Z', 
                        updated_at = '2025-06-25T12:00Z', )
                    ]
            )
        else:
            return AccreditationIndexByRegistryId200Response(
        )
        """

    def testAccreditationIndexByRegistryId200Response(self):
        """Test AccreditationIndexByRegistryId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
