# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisations_get_registries200_response_data_data_inner import OrganisationsGetRegistries200ResponseDataDataInner

class TestOrganisationsGetRegistries200ResponseDataDataInner(unittest.TestCase):
    """OrganisationsGetRegistries200ResponseDataDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationsGetRegistries200ResponseDataDataInner:
        """Test OrganisationsGetRegistries200ResponseDataDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationsGetRegistries200ResponseDataDataInner`
        """
        model = OrganisationsGetRegistries200ResponseDataDataInner()
        if include_optional:
            return OrganisationsGetRegistries200ResponseDataDataInner(
                registry_id = 56,
                organisation_id = 56
            )
        else:
            return OrganisationsGetRegistries200ResponseDataDataInner(
        )
        """

    def testOrganisationsGetRegistries200ResponseDataDataInner(self):
        """Test OrganisationsGetRegistries200ResponseDataDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
