# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisations_get_registries200_response_data import OrganisationsGetRegistries200ResponseData

class TestOrganisationsGetRegistries200ResponseData(unittest.TestCase):
    """OrganisationsGetRegistries200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationsGetRegistries200ResponseData:
        """Test OrganisationsGetRegistries200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationsGetRegistries200ResponseData`
        """
        model = OrganisationsGetRegistries200ResponseData()
        if include_optional:
            return OrganisationsGetRegistries200ResponseData(
                current_page = 56,
                data = [
                    safepeopleregistry_api_sdk.models.organisations_get_registries_200_response_data_data_inner.organisationsGetRegistries_200_response_data_data_inner(
                        registry_id = 56, 
                        organisation_id = 56, )
                    ],
                first_page_url = '',
                var_from = 56,
                last_page = 56,
                last_page_url = '',
                next_page_url = '',
                path = '',
                per_page = 56,
                prev_page_url = '',
                to = 56,
                total = 56
            )
        else:
            return OrganisationsGetRegistries200ResponseData(
        )
        """

    def testOrganisationsGetRegistries200ResponseData(self):
        """Test OrganisationsGetRegistries200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
