# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.custodian_project_organisations_get_status500_response import CustodianProjectOrganisationsGetStatus500Response

class TestCustodianProjectOrganisationsGetStatus500Response(unittest.TestCase):
    """CustodianProjectOrganisationsGetStatus500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodianProjectOrganisationsGetStatus500Response:
        """Test CustodianProjectOrganisationsGetStatus500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodianProjectOrganisationsGetStatus500Response`
        """
        model = CustodianProjectOrganisationsGetStatus500Response()
        if include_optional:
            return CustodianProjectOrganisationsGetStatus500Response(
                message = 'An error occurred: Unexpected error'
            )
        else:
            return CustodianProjectOrganisationsGetStatus500Response(
        )
        """

    def testCustodianProjectOrganisationsGetStatus500Response(self):
        """Test CustodianProjectOrganisationsGetStatus500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
