# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.organisation_get_delegates200_response_data_inner import OrganisationGetDelegates200ResponseDataInner

class TestOrganisationGetDelegates200ResponseDataInner(unittest.TestCase):
    """OrganisationGetDelegates200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganisationGetDelegates200ResponseDataInner:
        """Test OrganisationGetDelegates200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganisationGetDelegates200ResponseDataInner`
        """
        model = OrganisationGetDelegates200ResponseDataInner()
        if include_optional:
            return OrganisationGetDelegates200ResponseDataInner(
                id = 1,
                first_name = 'John',
                last_name = 'Doe',
                email = 'john.doe@example.com',
                created_at = '2023-06-01T12:00Z',
                updated_at = '2023-06-01T12:00Z'
            )
        else:
            return OrganisationGetDelegates200ResponseDataInner(
        )
        """

    def testOrganisationGetDelegates200ResponseDataInner(self):
        """Test OrganisationGetDelegates200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
