# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.files_show200_response_data import FilesShow200ResponseData

class TestFilesShow200ResponseData(unittest.TestCase):
    """FilesShow200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilesShow200ResponseData:
        """Test FilesShow200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilesShow200ResponseData`
        """
        model = FilesShow200ResponseData()
        if include_optional:
            return FilesShow200ResponseData(
                id = 1,
                name = 'users.csv',
                path = '1739297394_users.csv',
                type = 'RESEARCHERS_LIST',
                status = 'failed'
            )
        else:
            return FilesShow200ResponseData(
        )
        """

    def testFilesShow200ResponseData(self):
        """Test FilesShow200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
