# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.webhooks_get_all_event_triggers200_response import WebhooksGetAllEventTriggers200Response

class TestWebhooksGetAllEventTriggers200Response(unittest.TestCase):
    """WebhooksGetAllEventTriggers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhooksGetAllEventTriggers200Response:
        """Test WebhooksGetAllEventTriggers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhooksGetAllEventTriggers200Response`
        """
        model = WebhooksGetAllEventTriggers200Response()
        if include_optional:
            return WebhooksGetAllEventTriggers200Response(
                message = 'success',
                data = [
                    safepeopleregistry_api_sdk.models.webhooks_get_all_event_triggers_200_response_data_inner.webhooksGetAllEventTriggers_200_response_data_inner(
                        id = 1, 
                        name = 'user_created', 
                        description = 'Triggered when a new user is created', 
                        created_at = '2023-06-07T12:00Z', 
                        updated_at = '2023-06-07T12:00Z', )
                    ]
            )
        else:
            return WebhooksGetAllEventTriggers200Response(
        )
        """

    def testWebhooksGetAllEventTriggers200Response(self):
        """Test WebhooksGetAllEventTriggers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
