# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from safepeopleregistry_api_sdk.models.subsidiaries_store201_response import SubsidiariesStore201Response

class TestSubsidiariesStore201Response(unittest.TestCase):
    """SubsidiariesStore201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubsidiariesStore201Response:
        """Test SubsidiariesStore201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubsidiariesStore201Response`
        """
        model = SubsidiariesStore201Response()
        if include_optional:
            return SubsidiariesStore201Response(
                message = 'success',
                data = safepeopleregistry_api_sdk.models.subsidiary.Subsidiary(
                    id = 1, 
                    name = 'Subsidiary Name', 
                    address_1 = '123 Main Street', 
                    address_2 = 'Suite 456', 
                    town = 'Townsville', 
                    county = 'Countyshire', 
                    country = 'United Kingdom', 
                    postcode = 'AB12 3CD', 
                    website = 'https://www.subsidiary.com', 
                    is_parent = 1, )
            )
        else:
            return SubsidiariesStore201Response(
        )
        """

    def testSubsidiariesStore201Response(self):
        """Test SubsidiariesStore201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
