# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Education(BaseModel):
    """
    Model representing education records
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the education record", json_schema_extra={"examples": [1]})
    title: Optional[StrictStr] = Field(default=None, description="Title of the education qualification", json_schema_extra={"examples": ["Bachelor of Science in Computer Science"]})
    var_from: Optional[date] = Field(default=None, description="Start date of the education qualification", alias="from", json_schema_extra={"examples": ["2015-09-01"]})
    to: Optional[date] = Field(default=None, description="End date of the education qualification", json_schema_extra={"examples": ["2019-06-30"]})
    institute_name: Optional[StrictStr] = Field(default=None, description="Name of the educational institute", json_schema_extra={"examples": ["University of Example"]})
    institute_address: Optional[StrictStr] = Field(default=None, description="Address of the educational institute", json_schema_extra={"examples": ["123 University Lane, Example City"]})
    institute_identifier: Optional[StrictStr] = Field(default=None, description="Identifier for the educational institute", json_schema_extra={"examples": ["https://ror.org/12345"]})
    source: Optional[StrictStr] = Field(default=None, description="Source of the education record", json_schema_extra={"examples": ["Self-reported"]})
    registry_id: Optional[StrictInt] = Field(default=None, description="ID of the registry associated with the education record", json_schema_extra={"examples": [42]})
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the education record was created", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the education record was last updated", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    __properties: ClassVar[List[str]] = ["id", "title", "from", "to", "institute_name", "institute_address", "institute_identifier", "source", "registry_id", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Education from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Education from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "institute_name": obj.get("institute_name"),
            "institute_address": obj.get("institute_address"),
            "institute_identifier": obj.get("institute_identifier"),
            "source": obj.get("source"),
            "registry_id": obj.get("registry_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


