# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EntityModel(BaseModel):
    """
    Model representing entity models
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the entity model", json_schema_extra={"examples": [1]})
    name: Optional[StrictStr] = Field(default=None, description="Name of the entity model", json_schema_extra={"examples": ["Data Processing Model"]})
    description: Optional[StrictStr] = Field(default=None, description="Description of the entity model", json_schema_extra={"examples": ["This model processes data based on predefined rules."]})
    entity_model_type_id: Optional[StrictInt] = Field(default=None, description="ID of the entity model type associated with this model", json_schema_extra={"examples": [2]})
    calls_file: Optional[StrictBool] = Field(default=None, description="Indicates whether the model calls a file", json_schema_extra={"examples": [True]})
    file_path: Optional[StrictStr] = Field(default=None, description="Path to the file called by the model", json_schema_extra={"examples": ["/path/to/file"]})
    calls_operation: Optional[StrictBool] = Field(default=None, description="Indicates whether the model calls an operation", json_schema_extra={"examples": [False]})
    operation: Optional[StrictStr] = Field(default=None, description="Operation called by the model", json_schema_extra={"examples": ["processData"]})
    active: Optional[StrictInt] = Field(default=None, description="Indicates whether the model is active (1 for active, 0 for inactive)", json_schema_extra={"examples": [1]})
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the entity model was created", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the entity model was last updated", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    __properties: ClassVar[List[str]] = ["id", "name", "description", "entity_model_type_id", "calls_file", "file_path", "calls_operation", "operation", "active", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "entity_model_type_id": obj.get("entity_model_type_id"),
            "calls_file": obj.get("calls_file"),
            "file_path": obj.get("file_path"),
            "calls_operation": obj.get("calls_operation"),
            "operation": obj.get("operation"),
            "active": obj.get("active"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


