# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Experience(BaseModel):
    """
    Model representing experiences
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the experience", json_schema_extra={"examples": [1]})
    project_id: Optional[StrictInt] = Field(default=None, description="ID of the project associated with the experience", json_schema_extra={"examples": [42]})
    var_from: Optional[date] = Field(default=None, description="Start date of the experience", alias="from", json_schema_extra={"examples": ["2020-01-01"]})
    to: Optional[date] = Field(default=None, description="End date of the experience", json_schema_extra={"examples": ["2022-12-31"]})
    organisation_id: Optional[StrictInt] = Field(default=None, description="ID of the organisation associated with the experience", json_schema_extra={"examples": [24]})
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the experience was created", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the experience was last updated", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    __properties: ClassVar[List[str]] = ["id", "project_id", "from", "to", "organisation_id", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Experience from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Experience from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "organisation_id": obj.get("organisation_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


