# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from safepeopleregistry_api_sdk.models.organisation_get_users200_response_data_data_inner import OrganisationGetUsers200ResponseDataDataInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrganisationGetUsers200ResponseData(BaseModel):
    """
    OrganisationGetUsers200ResponseData
    """ # noqa: E501
    current_page: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    data: Optional[List[OrganisationGetUsers200ResponseDataDataInner]] = None
    first_page_url: Optional[StrictStr] = None
    var_from: Optional[StrictInt] = Field(default=None, alias="from")
    last_page: Optional[StrictInt] = None
    last_page_url: Optional[StrictStr] = None
    next_page_url: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    per_page: Optional[StrictInt] = None
    prev_page_url: Optional[StrictStr] = None
    to: Optional[StrictInt] = None
    total: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["current_page", "data", "first_page_url", "from", "last_page", "last_page_url", "next_page_url", "path", "per_page", "prev_page_url", "to", "total"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganisationGetUsers200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganisationGetUsers200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_page": obj.get("current_page"),
            "data": [OrganisationGetUsers200ResponseDataDataInner.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "first_page_url": obj.get("first_page_url"),
            "from": obj.get("from"),
            "last_page": obj.get("last_page"),
            "last_page_url": obj.get("last_page_url"),
            "next_page_url": obj.get("next_page_url"),
            "path": obj.get("path"),
            "per_page": obj.get("per_page"),
            "prev_page_url": obj.get("prev_page_url"),
            "to": obj.get("to"),
            "total": obj.get("total")
        })
        return _obj


