# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProjectUpdate200ResponseData(BaseModel):
    """
    ProjectUpdate200ResponseData
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [123]})
    created_at: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2024-02-04 12:00:00"]})
    updated_at: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2024-02-04 12:01:00"]})
    registry_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["My First Research Project"]})
    public_benefit: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["A public benefit statement"]})
    runs_to: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2026-02-04"]})
    status: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["approved"]})
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "registry_id", "name", "public_benefit", "runs_to", "status"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProjectUpdate200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProjectUpdate200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "registry_id": obj.get("registry_id"),
            "name": obj.get("name"),
            "public_benefit": obj.get("public_benefit"),
            "runs_to": obj.get("runs_to"),
            "status": obj.get("status")
        })
        return _obj


