# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from safepeopleregistry_api_sdk.models.affiliation import Affiliation
from safepeopleregistry_api_sdk.models.project import Project
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryQuery200ResponseDataRegistryAllOfHistoryInner(BaseModel):
    """
    QueryQuery200ResponseDataRegistryAllOfHistoryInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the history record", json_schema_extra={"examples": [1]})
    affiliation_id: Optional[StrictInt] = Field(default=None, description="ID of the affiliation associated with the history record", json_schema_extra={"examples": [42]})
    endorsement_id: Optional[StrictInt] = Field(default=None, description="ID of the endorsement associated with the history record", json_schema_extra={"examples": [24]})
    infringement_id: Optional[StrictInt] = Field(default=None, description="ID of the infringement associated with the history record", json_schema_extra={"examples": [12]})
    project_id: Optional[StrictInt] = Field(default=None, description="ID of the project associated with the history record", json_schema_extra={"examples": [100]})
    access_key_id: Optional[StrictInt] = Field(default=None, description="ID of the access key associated with the history record", json_schema_extra={"examples": [5]})
    custodian_identifier: Optional[StrictStr] = Field(default=None, description="Identifier for the custodian associated with the history record", json_schema_extra={"examples": ["CUST12345"]})
    ledger_hash: Optional[StrictStr] = Field(default=None, description="Hash of the ledger associated with the history record", json_schema_extra={"examples": ["abc123hash"]})
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the history record was created", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the history record was last updated", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    affiliation: Optional[Affiliation] = None
    project: Optional[Project] = None
    __properties: ClassVar[List[str]] = ["id", "affiliation_id", "endorsement_id", "infringement_id", "project_id", "access_key_id", "custodian_identifier", "ledger_hash", "created_at", "updated_at", "affiliation", "project"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryQuery200ResponseDataRegistryAllOfHistoryInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of affiliation
        if self.affiliation:
            _dict['affiliation'] = self.affiliation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # set to None if affiliation (nullable) is None
        # and model_fields_set contains the field
        if self.affiliation is None and "affiliation" in self.model_fields_set:
            _dict['affiliation'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryQuery200ResponseDataRegistryAllOfHistoryInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "affiliation_id": obj.get("affiliation_id"),
            "endorsement_id": obj.get("endorsement_id"),
            "infringement_id": obj.get("infringement_id"),
            "project_id": obj.get("project_id"),
            "access_key_id": obj.get("access_key_id"),
            "custodian_identifier": obj.get("custodian_identifier"),
            "ledger_hash": obj.get("ledger_hash"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "affiliation": Affiliation.from_dict(obj["affiliation"]) if obj.get("affiliation") is not None else None,
            "project": Project.from_dict(obj["project"]) if obj.get("project") is not None else None
        })
        return _obj


