# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from safepeopleregistry_api_sdk.models.query_query200_response_data_registry_all_of_history_inner import QueryQuery200ResponseDataRegistryAllOfHistoryInner
from safepeopleregistry_api_sdk.models.training import Training
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueryQuery200ResponseDataRegistry(BaseModel):
    """
    The matched Registry record
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    created_at: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2024-02-04 12:01:00"]})
    updated_at: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2024-02-04 12:01:00"]})
    deleted_at: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["2024-02-04 12:01:00"]})
    digi_ident: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["$2y$12$Ssrz04d0bfw2X9t3juq9K.WPUgPNplXr1FHbdjoTeLajgVGGRxiqG"]})
    dl_ident: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": [""]})
    pp_ident: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": [""]})
    verified: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    training: Optional[List[Training]] = Field(default=None, description="Training records linked to the registry")
    history: Optional[List[QueryQuery200ResponseDataRegistryAllOfHistoryInner]] = Field(default=None, description="History records linked to the registry, each with its related affiliation and project")
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "deleted_at", "digi_ident", "dl_ident", "pp_ident", "verified", "training", "history"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryQuery200ResponseDataRegistry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in training (list)
        _items = []
        if self.training:
            for _item_training in self.training:
                if _item_training:
                    _items.append(_item_training.to_dict())
            _dict['training'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict['history'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryQuery200ResponseDataRegistry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at"),
            "digi_ident": obj.get("digi_ident"),
            "dl_ident": obj.get("dl_ident"),
            "pp_ident": obj.get("pp_ident"),
            "verified": obj.get("verified"),
            "training": [Training.from_dict(_item) for _item in obj["training"]] if obj.get("training") is not None else None,
            "history": [QueryQuery200ResponseDataRegistryAllOfHistoryInner.from_dict(_item) for _item in obj["history"]] if obj.get("history") is not None else None
        })
        return _obj


