# coding: utf-8

"""
    Safe People Registry API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UksaLiveFeed(BaseModel):
    """
    Model representing UKSA live feed data
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the UKSA live feed record", json_schema_extra={"examples": [1]})
    first_name: Optional[StrictStr] = Field(default=None, description="First name of the individual", json_schema_extra={"examples": ["John"]})
    last_name: Optional[StrictStr] = Field(default=None, description="Last name of the individual", json_schema_extra={"examples": ["Doe"]})
    organisation_name: Optional[StrictStr] = Field(default=None, description="Name of the organisation", json_schema_extra={"examples": ["Health Data Research UK"]})
    accreditation_number: Optional[StrictStr] = Field(default=None, description="Accreditation number", json_schema_extra={"examples": ["ACC12345"]})
    accreditation_type: Optional[StrictStr] = Field(default=None, description="Type of accreditation", json_schema_extra={"examples": ["Type A"]})
    expiry_date: Optional[date] = Field(default=None, description="Expiry date of the accreditation", json_schema_extra={"examples": ["2025-12-31"]})
    public_record: Optional[StrictStr] = Field(default=None, description="Indicates whether the record is public", json_schema_extra={"examples": ["Yes"]})
    stage: Optional[StrictStr] = Field(default=None, description="Current stage of the accreditation process", json_schema_extra={"examples": ["Approved"]})
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the record was created", json_schema_extra={"examples": ["2025-06-25T12:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the record was last updated", json_schema_extra={"examples": ["2025-06-26T12:00:00Z"]})
    __properties: ClassVar[List[str]] = ["id", "first_name", "last_name", "organisation_name", "accreditation_number", "accreditation_type", "expiry_date", "public_record", "stage", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UksaLiveFeed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UksaLiveFeed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "organisation_name": obj.get("organisation_name"),
            "accreditation_number": obj.get("accreditation_number"),
            "accreditation_type": obj.get("accreditation_type"),
            "expiry_date": obj.get("expiry_date"),
            "public_record": obj.get("public_record"),
            "stage": obj.get("stage"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


